apiVersion: v2
type: application
name: vikunja
home: https://kolaente.dev/vikunja/helm-chart
icon: https://kolaente.dev/vikunja/helm-chart/raw/main/icon.png
deprecated: false
description: |-
  The open-source, self-hostable to-do app. Organize everything, on all platforms.
annotations:
  category: TaskTracker
version: 1.0.0
appVersion: 0.24.6
kubeVersion: ">= 1.19"
dependencies:
- name: redis
  repository: https://charts.bitnami.com/bitnami
  # TODO Consider switch to valkey - staying with pre-fork redis 7.2.4 for now
  version: 18.6.3
  condition: redis.enabled
- name: postgresql
  repository: https://charts.bitnami.com/bitnami
  # https://github.com/bitnami/charts/blob/main/bitnami/postgresql/Chart.yaml
  version: 16.4.5 # Postgres 17.2
  condition: postgresql.enabled
- name: common
  repository: https://bjw-s.github.io/helm-charts
  version: 1.5.1
keywords:
- vikunja
- todo
- to-do
- task
- task-tracker
- project-management
- self-hosted
maintainers:
- name: Vikunja
  url: https://vikunja.io
sources:
- https://kolaente.dev/vikunja/helm-chart
- https://vikunja.io
